# ==========================================================
# 1. CONFIGURACIÓN GLOBAL (Aplicada a todos los microservicios)
# ==========================================================

# A. Configuración de JPA/Hibernate
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.main.allow-bean-definition-overriding=true

# B. Configuración de la Base de Datos (Común a todos los que usan BD)
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

springdoc.swagger-ui.path=/swagger-ui/index.html
springdoc.api-docs.path=/v3/api-docs