# ==========================================================
# CONFIGURACIÓN ESPECÍFICA (workflow-service)
# ==========================================================

# 1. IDENTIFICACIÓN Y PUERTO
spring.application.name=workflow-service
server.port=8086

# 2. VARIABLE DE JWT
workflow.jwt.secret=${JWT_SECRET:26f4dd71e8264f1aa8414884cc9d90ad}
workflow.jwt.access-expiration=${AUTH_JWT_ACCESS_EXPIRATION}
workflow.jwt.refresh-expiration=${AUTH_JWT_REFRESH_EXPIRATION}
workflow.api.key=${API_KEY:123456789-MI-CLAVE}

# 3. REQUEST FILE
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=200MB

# 4. VARIABLE PARA PASAR A GENERAL
general.service.url=GENERAL-SERVICE

# 5. VARIABLE PATH
server.servlet.context-path=/workflow